export interface Station {
  code: string;
  name: string;
}

// List of Dutch train stations with their abbreviation codes
// Excludes event-only stations and bus stops
export const stations: Station[] = [
  { code: 'Atn', name: 'Aalten' },
  { code: 'Ac', name: 'Abcoude' },
  { code: 'Akm', name: 'Akkrum' },
  { code: 'Amr', name: 'Alkmaar' },
  { code: 'Amrn', name: 'Alkmaar Noord' },
  { code: 'Aml', name: 'Almelo' },
  { code: 'Amri', name: 'Almelo de Riet' },
  { code: 'Almb', name: 'Almere Buiten' },
  { code: 'Alm', name: 'Almere Centrum' },
  { code: 'Almm', name: 'Almere Muziekwijk' },
  { code: 'Almo', name: 'Almere Oostvaarders' },
  { code: 'Almp', name: 'Almere Parkwijk' },
  { code: 'Ampo', name: 'Almere Poort' },
  { code: 'Apn', name: 'Alphen aan den Rijn' },
  { code: 'Amf', name: 'Amersfoort Centraal' },
  { code: 'Amfs', name: 'Amersfoort Schothorst' },
  { code: 'Avat', name: 'Amersfoort Vathorst' },
  { code: 'Asa', name: 'Amsterdam Amstel' },
  { code: 'Asb', name: 'Amsterdam Bijlmer ArenA' },
  { code: 'Asd', name: 'Amsterdam Centraal' },
  { code: 'Asdh', name: 'Amsterdam Holendrecht' },
  { code: 'Asdl', name: 'Amsterdam Lelylaan' },
  { code: 'Asdm', name: 'Amsterdam Muiderpoort' },
  { code: 'Rai', name: 'Amsterdam RAI' },
  { code: 'Assp', name: 'Amsterdam Science Park' },
  { code: 'Ass', name: 'Amsterdam Sloterdijk' },
  { code: 'Asdz', name: 'Amsterdam Zuid' },
  { code: 'Ana', name: 'Anna Paulowna' },
  { code: 'Apd', name: 'Apeldoorn' },
  { code: 'Apdm', name: 'Apeldoorn De Maten' },
  { code: 'Apdo', name: 'Apeldoorn Osseveld' },
  { code: 'Apg', name: 'Appingedam' },
  { code: 'Akl', name: 'Arkel' },
  { code: 'Arn', name: 'Arnemuiden' },
  { code: 'Ah', name: 'Arnhem Centraal' },
  { code: 'Ahpr', name: 'Arnhem Presikhaaf' },
  { code: 'Ahp', name: 'Arnhem Velperpoort' },
  { code: 'Ahz', name: 'Arnhem Zuid' },
  { code: 'Asn', name: 'Assen' },
  { code: 'Brn', name: 'Baarn' },
  { code: 'Bf', name: 'Baflo' },
  { code: 'Brd', name: 'Barendrecht' },
  { code: 'Bnc', name: 'Barneveld Centrum' },
  { code: 'Bnn', name: 'Barneveld Noord' },
  { code: 'Bdm', name: 'Bedum' },
  { code: 'Bk', name: 'Beek-Elsloo' },
  { code: 'Bsd', name: 'Beesd' },
  { code: 'Bl', name: 'Beilen' },
  { code: 'Bgn', name: 'Bergen op Zoom' },
  { code: 'Bet', name: 'Best' },
  { code: 'Bv', name: 'Beverwijk' },
  { code: 'Bhv', name: 'Bilthoven' },
  { code: 'Br', name: 'Blerick' },
  { code: 'Bll', name: 'Bloemendaal' },
  { code: 'Bdg', name: 'Bodegraven' },
  { code: 'Bn', name: 'Borne' },
  { code: 'Bsk', name: 'Boskoop' },
  { code: 'Bsks', name: 'Boskoop Snijdelwijk' },
  { code: 'Bhdv', name: 'Boven-Hardinxveld' },
  { code: 'Bkf', name: 'Bovenkarspel Flora' },
  { code: 'Bkg', name: 'Bovenkarspel-Grootebroek' },
  { code: 'Bmr', name: 'Boxmeer' },
  { code: 'Btl', name: 'Boxtel' },
  { code: 'Bd', name: 'Breda' },
  { code: 'Bdpb', name: 'Breda-Prinsenbeek' },
  { code: 'Bkl', name: 'Breukelen' },
  { code: 'Bmn', name: 'Brummen' },
  { code: 'Bp', name: 'Buitenpost' },
  { code: 'Bde', name: 'Bunde' },
  { code: 'Bnk', name: 'Bunnik' },
  { code: 'Bsmz', name: 'Bussum Zuid' },
  { code: 'Cps', name: 'Capelle Schollevaar' },
  { code: 'Cas', name: 'Castricum' },
  { code: 'Cvm', name: 'Chevremont' },
  { code: 'Co', name: 'Coevorden' },
  { code: 'Ck', name: 'Cuijk' },
  { code: 'Cl', name: 'Culemborg' },
  { code: 'Da', name: 'Daarlerveen' },
  { code: 'Dln', name: 'Dalen' },
  { code: 'Dl', name: 'Dalfsen' },
  { code: 'Dvnk', name: 'De Vink' },
  { code: 'Dei', name: 'Deinum' },
  { code: 'Ddn', name: 'Delden' },
  { code: 'Dt', name: 'Delft' },
  { code: 'Dtz', name: 'Delft Campus' },
  { code: 'Dz', name: 'Delfzijl' },
  { code: 'Dzw', name: 'Delfzijl West' },
  { code: 'Dld', name: 'Den Dolder' },
  { code: 'Gvc', name: 'Den Haag Centraal' },
  { code: 'Gv', name: 'Den Haag HS' },
  { code: 'Laa', name: 'Den Haag Laan van NOI' },
  { code: 'Gvm', name: 'Den Haag Mariahoeve' },
  { code: 'Gvmw', name: 'Den Haag Moerwijk' },
  { code: 'Ypb', name: 'Den Haag Ypenburg' },
  { code: 'Hdr', name: 'Den Helder' },
  { code: 'Hdrz', name: 'Den Helder Zuid' },
  { code: 'Dn', name: 'Deurne' },
  { code: 'Dv', name: 'Deventer' },
  { code: 'Dvc', name: 'Deventer Colmschate' },
  { code: 'Dwe', name: 'De Westereen' },
  { code: 'Did', name: 'Didam' },
  { code: 'Dmn', name: 'Diemen' },
  { code: 'Dmnz', name: 'Diemen Zuid' },
  { code: 'Dr', name: 'Dieren' },
  { code: 'Dtc', name: 'Doetinchem' },
  { code: 'Dtch', name: 'Doetinchem De Huet' },
  { code: 'Ddr', name: 'Dordrecht' },
  { code: 'Ddrs', name: 'Dordrecht Stadspolders' },
  { code: 'Ddzd', name: 'Dordrecht Zuid' },
  { code: 'Db', name: 'Driebergen-Zeist' },
  { code: 'Drh', name: 'Driehuis' },
  { code: 'Drp', name: 'Dronryp' },
  { code: 'Dron', name: 'Dronten' },
  { code: 'Dvn', name: 'Duiven' },
  { code: 'Dvd', name: 'Duivendrecht' },
  { code: 'Ec', name: 'Echt' },
  { code: 'Edc', name: 'Ede Centrum' },
  { code: 'Ed', name: 'Ede-Wageningen' },
  { code: 'Eem', name: 'Eemshaven' },
  { code: 'Edn', name: 'Eijsden' },
  { code: 'Ehv', name: 'Eindhoven Centraal' },
  { code: 'Ehs', name: 'Eindhoven Strijp-S' },
  { code: 'Est', name: 'Elst' },
  { code: 'Emn', name: 'Emmen' },
  { code: 'Emnz', name: 'Emmen Zuid' },
  { code: 'Ekz', name: 'Enkhuizen' },
  { code: 'Es', name: 'Enschede' },
  { code: 'Ese', name: 'Enschede De Eschmarke' },
  { code: 'Esk', name: 'Enschede Kennispark' },
  { code: 'Eml', name: 'Ermelo' },
  { code: 'Etn', name: 'Etten-Leur' },
  { code: 'Egh', name: 'Eygelshoven' },
  { code: 'Eghm', name: 'Eygelshoven Markt' },
  { code: 'Fwd', name: 'Feanwâlden' },
  { code: 'Fn', name: 'Franeker' },
  { code: 'Gdr', name: 'Gaanderen' },
  { code: 'Gdm', name: 'Geldermalsen' },
  { code: 'Gp', name: 'Geldrop' },
  { code: 'Gln', name: 'Geleen Oost' },
  { code: 'Lut', name: 'Geleen-Lutterade' },
  { code: 'Gz', name: 'Gilze-Rijen' },
  { code: 'Gbr', name: 'Glanerbrug' },
  { code: 'Gs', name: 'Goes' },
  { code: 'Go', name: 'Goor' },
  { code: 'Gr', name: 'Gorinchem' },
  { code: 'Gd', name: 'Gouda' },
  { code: 'Gdg', name: 'Gouda Goverwelle' },
  { code: 'Gbg', name: 'Gramsbergen' },
  { code: 'Gk', name: 'Grijpskerk' },
  { code: 'Gn', name: 'Groningen' },
  { code: 'Gerp', name: 'Groningen Europapark' },
  { code: 'Gnn', name: 'Groningen Noord' },
  { code: 'Gw', name: 'Grou-Jirnsum' },
  { code: 'Hlm', name: 'Haarlem' },
  { code: 'Hlms', name: 'Haarlem Spaarnwoude' },
  { code: 'Hwzw', name: 'Halfweg-Zwanenburg' },
  { code: 'Hde', name: "'t Harde" },
  { code: 'Hdb', name: 'Hardenberg' },
  { code: 'Hd', name: 'Harderwijk' },
  { code: 'Hbzm', name: 'Hardinxveld Blauwe Zoom' },
  { code: 'Gnd', name: 'Hardinxveld-Giessendam' },
  { code: 'Hrn', name: 'Haren' },
  { code: 'Hlg', name: 'Harlingen' },
  { code: 'Hlgh', name: 'Harlingen Haven' },
  { code: 'Hk', name: 'Heemskerk' },
  { code: 'Had', name: 'Heemstede-Aerdenhout' },
  { code: 'Hr', name: 'Heerenveen' },
  { code: 'Hwd', name: 'Heerhugowaard' },
  { code: 'Hrl', name: 'Heerlen' },
  { code: 'Hrlw', name: 'Heerlen Woonboulevard' },
  { code: 'Hze', name: 'Heeze' },
  { code: 'Hlo', name: 'Heiloo' },
  { code: 'Hno', name: 'Heino' },
  { code: 'Hm', name: 'Helmond' },
  { code: 'Hmbv', name: 'Helmond Brandevoort' },
  { code: 'Hmbh', name: 'Helmond Brouwhuis' },
  { code: 'Hmh', name: "Helmond 't Hout" },
  { code: 'Hmn', name: 'Hemmen-Dodewaard' },
  { code: 'Hgl', name: 'Hengelo' },
  { code: 'Hglg', name: 'Hengelo Gezondheidspark' },
  { code: 'Hglo', name: 'Hengelo Oost' },
  { code: 'Ht', name: "'s-Hertogenbosch" },
  { code: 'Hto', name: "'s-Hertogenbosch Oost" },
  { code: 'Hil', name: 'Hillegom' },
  { code: 'Hvs', name: 'Hilversum' },
  { code: 'Hvsn', name: 'Hilversum Noord' },
  { code: 'Hvsp', name: 'Hilversum Sportpark' },
  { code: 'Hnp', name: 'Hindeloopen' },
  { code: 'Hb', name: 'Hoensbroek' },
  { code: 'Hvl', name: 'Hoevelaken' },
  { code: 'Hor', name: 'Hollandsche Rading' },
  { code: 'Hon', name: 'Holten' },
  { code: 'Hfd', name: 'Hoofddorp' },
  { code: 'Hgv', name: 'Hoogeveen' },
  { code: 'Hgz', name: 'Hoogezand-Sappemeer' },
  { code: 'Hks', name: 'Hoogkarspel' },
  { code: 'Hn', name: 'Hoorn' },
  { code: 'Hnk', name: 'Hoorn Kersenboogerd' },
  { code: 'Hrt', name: 'Horst-Sevenum' },
  { code: 'Htn', name: 'Houten' },
  { code: 'Htnc', name: 'Houten Castellum' },
  { code: 'Sgl', name: 'Houthem-St. Gerlach' },
  { code: 'Hdg', name: 'Hurdegaryp' },
  { code: 'IJt', name: 'IJlst' },
  { code: 'Kpn', name: 'Kampen' },
  { code: 'Kpnz', name: 'Kampen Zuid' },
  { code: 'Bzl', name: 'Kapelle-Biezelinge' },
  { code: 'Krd', name: 'Kerkrade Centrum' },
  { code: 'Ktr', name: 'Kesteren' },
  { code: 'Kbk', name: 'Klarenbeek' },
  { code: 'Kmr', name: 'Klimmen-Ransdaal' },
  { code: 'Kz', name: 'Koog aan de Zaan' },
  { code: 'Kmw', name: 'Koudum-Molkwerum' },
  { code: 'Kbd', name: 'Krabbendijke' },
  { code: 'Kma', name: 'Krommenie-Assendelft' },
  { code: 'Kw', name: 'Kropswolde' },
  { code: 'Krg', name: 'Kruiningen-Yerseke' },
  { code: 'Zlw', name: 'Lage Zwaluwe' },
  { code: 'Lg', name: 'Landgraaf' },
  { code: 'Llzm', name: 'Lansingerland-Zoetermeer' },
  { code: 'Ldm', name: 'Leerdam' },
  { code: 'Lw', name: 'Leeuwarden' },
  { code: 'Lwc', name: 'Leeuwarden Camminghaburen' },
  { code: 'Ledn', name: 'Leiden Centraal' },
  { code: 'Ldl', name: 'Leiden Lammenschans' },
  { code: 'Lls', name: 'Lelystad Centrum' },
  { code: 'Ltv', name: 'Lichtenvoorde-Groenlo' },
  { code: 'Lc', name: 'Lochem' },
  { code: 'Lp', name: 'Loppersum' },
  { code: 'Ltn', name: 'Lunteren' },
  { code: 'Mz', name: 'Maarheeze' },
  { code: 'Mrn', name: 'Maarn' },
  { code: 'Mas', name: 'Maarssen' },
  { code: 'Mt', name: 'Maastricht' },
  { code: 'Mtn', name: 'Maastricht Noord' },
  { code: 'Mtr', name: 'Maastricht Randwyck' },
  { code: 'Mg', name: 'Mantgum' },
  { code: 'Mrb', name: 'Mariënberg' },
  { code: 'Mth', name: 'Martenshoek' },
  { code: 'Mes', name: 'Meerssen' },
  { code: 'Mp', name: 'Meppel' },
  { code: 'Mdb', name: 'Middelburg' },
  { code: 'Mmlh', name: 'Mook-Molenhoek' },
  { code: 'Ndb', name: 'Naarden-Bussum' },
  { code: 'Na', name: 'Nieuw Amsterdam' },
  { code: 'Nvp', name: 'Nieuw Vennep' },
  { code: 'Nwk', name: 'Nieuwerkerk aan den IJssel' },
  { code: 'Nsch', name: 'Bad Nieuweschans' },
  { code: 'Nkk', name: 'Nijkerk' },
  { code: 'Nm', name: 'Nijmegen' },
  { code: 'Nmd', name: 'Nijmegen Dukenburg' },
  { code: 'Nmgo', name: 'Nijmegen Goffert' },
  { code: 'Nmh', name: 'Nijmegen Heyendaal' },
  { code: 'Nml', name: 'Nijmegen Lent' },
  { code: 'Nvd', name: 'Nijverdal' },
  { code: 'Ns', name: 'Nunspeet' },
  { code: 'Nh', name: 'Nuth' },
  { code: 'Obd', name: 'Obdam' },
  { code: 'Ot', name: 'Oisterwijk' },
  { code: 'Odz', name: 'Oldenzaal' },
  { code: 'Ost', name: 'Olst' },
  { code: 'Omn', name: 'Ommen' },
  { code: 'Otb', name: 'Oosterbeek' },
  { code: 'Op', name: 'Opheusden' },
  { code: 'O', name: 'Oss' },
  { code: 'Ow', name: 'Oss West' },
  { code: 'Odb', name: 'Oudenbosch' },
  { code: 'Ovn', name: 'Overveen' },
  { code: 'Pmr', name: 'Purmerend' },
  { code: 'Pmo', name: 'Purmerend Overwhere' },
  { code: 'Pmw', name: 'Purmerend Weidevenne' },
  { code: 'Pt', name: 'Putten' },
  { code: 'Rat', name: 'Raalte' },
  { code: 'Rvs', name: 'Ravenstein' },
  { code: 'Rv', name: 'Reuver' },
  { code: 'Rh', name: 'Rheden' },
  { code: 'Rhn', name: 'Rhenen' },
  { code: 'Rsn', name: 'Rijssen' },
  { code: 'Rsw', name: 'Rijswijk' },
  { code: 'Rb', name: 'Rilland-Bath' },
  { code: 'Rm', name: 'Roermond' },
  { code: 'Rd', name: 'Roodeschool' },
  { code: 'Rsd', name: 'Roosendaal' },
  { code: 'Rs', name: 'Rosmalen' },
  { code: 'Rta', name: 'Rotterdam Alexander' },
  { code: 'Rtb', name: 'Rotterdam Blaak' },
  { code: 'Rtd', name: 'Rotterdam Centraal' },
  { code: 'Rlb', name: 'Rotterdam Lombardijen' },
  { code: 'Rtn', name: 'Rotterdam Noord' },
  { code: 'Rtz', name: 'Rotterdam Zuid' },
  { code: 'Rl', name: 'Ruurlo' },
  { code: 'Sptn', name: 'Santpoort Noord' },
  { code: 'Sptz', name: 'Santpoort Zuid' },
  { code: 'Spm', name: 'Sappemeer Oost' },
  { code: 'Ssh', name: 'Sassenheim' },
  { code: 'Swd', name: 'Sauwerd' },
  { code: 'Sgn', name: 'Schagen' },
  { code: 'Sda', name: 'Scheemda' },
  { code: 'Sdm', name: 'Schiedam Centrum' },
  { code: 'Sn', name: 'Schinnen' },
  { code: 'Sog', name: 'Schin op Geul' },
  { code: 'Shl', name: 'Schiphol Airport' },
  { code: 'Std', name: 'Sittard' },
  { code: 'Sk', name: 'Sneek' },
  { code: 'Sknd', name: 'Sneek Noord' },
  { code: 'St', name: 'Soest' },
  { code: 'Stz', name: 'Soest Zuid' },
  { code: 'Sd', name: 'Soestdijk' },
  { code: 'Sdtb', name: 'Sliedrecht Baanhoek' },
  { code: 'Sbk', name: 'Spaubeek' },
  { code: 'Stv', name: 'Stavoren' },
  { code: 'Stm', name: 'Stedum' },
  { code: 'Swk', name: 'Steenwijk' },
  { code: 'Srn', name: 'Susteren' },
  { code: 'Sm', name: 'Swalmen' },
  { code: 'Tg', name: 'Tegelen' },
  { code: 'Tbg', name: 'Terborg' },
  { code: 'Tl', name: 'Tiel' },
  { code: 'Tpsw', name: 'Tiel Passewaaij' },
  { code: 'Tb', name: 'Tilburg' },
  { code: 'Tbr', name: 'Tilburg Reeshof' },
  { code: 'Tbu', name: 'Tilburg Universiteit' },
  { code: 'Twl', name: 'Twello' },
  { code: 'Utg', name: 'Uitgeest' },
  { code: 'Uhz', name: 'Uithuizen' },
  { code: 'Uhm', name: 'Uithuizermeeden' },
  { code: 'Ust', name: 'Usquert' },
  { code: 'Ut', name: 'Utrecht Centraal' },
  { code: 'Utlr', name: 'Utrecht Leidsche Rijn' },
  { code: 'Utln', name: 'Utrecht Lunetten' },
  { code: 'Utm', name: 'Utrecht Maliebaan' },
  { code: 'Uto', name: 'Utrecht Overvecht' },
  { code: 'Utt', name: 'Utrecht Terwijde' },
  { code: 'Utvr', name: 'Utrecht Vaartsche Rijn' },
  { code: 'Utzl', name: 'Utrecht Zuilen' },
  { code: 'Vk', name: 'Valkenburg' },
  { code: 'Vsv', name: 'Varsseveld' },
  { code: 'Vdm', name: 'Veendam' },
  { code: 'Vndc', name: 'Veenendaal Centrum' },
  { code: 'Klp', name: 'Veenendaal-De Klomp' },
  { code: 'Vndw', name: 'Veenendaal West' },
  { code: 'Vp', name: 'Velp' },
  { code: 'Vl', name: 'Venlo' },
  { code: 'Vry', name: 'Venray' },
  { code: 'Vlb', name: 'Vierlingsbeek' },
  { code: 'Vtn', name: 'Vleuten' },
  { code: 'Vs', name: 'Vlissingen' },
  { code: 'Vss', name: 'Vlissingen Souburg' },
  { code: 'Vdl', name: 'Voerendaal' },
  { code: 'Vb', name: 'Voorburg' },
  { code: 'Vh', name: 'Voorhout' },
  { code: 'Vst', name: 'Voorschoten' },
  { code: 'Vem', name: 'Voorst-Empe' },
  { code: 'Vd', name: 'Vorden' },
  { code: 'Vz', name: 'Vriezenveen' },
  { code: 'Vhp', name: 'Vroomshoop' },
  { code: 'Vg', name: 'Vught' },
  { code: 'Wad', name: 'Waddinxveen' },
  { code: 'Wadn', name: 'Waddinxveen Noord' },
  { code: 'Wadt', name: 'Waddinxveen Triangel' },
  { code: 'Wfm', name: 'Warffum' },
  { code: 'Wt', name: 'Weert' },
  { code: 'Wp', name: 'Weesp' },
  { code: 'Wl', name: 'Wehl' },
  { code: 'Wtv', name: 'Westervoort' },
  { code: 'Wz', name: 'Wezep' },
  { code: 'Wdn', name: 'Wierden' },
  { code: 'Wc', name: 'Wijchen' },
  { code: 'Wh', name: 'Wijhe' },
  { code: 'Ws', name: 'Winschoten' },
  { code: 'Wsm', name: 'Winsum' },
  { code: 'Ww', name: 'Winterswijk' },
  { code: 'Www', name: 'Winterswijk West' },
  { code: 'Wd', name: 'Woerden' },
  { code: 'Wf', name: 'Wolfheze' },
  { code: 'Wv', name: 'Wolvega' },
  { code: 'Wk', name: 'Workum' },
  { code: 'Wm', name: 'Wormerveer' },
  { code: 'Zd', name: 'Zaandam' },
  { code: 'Zdk', name: 'Zaandam Kogerveld' },
  { code: 'Zbm', name: 'Zaltbommel' },
  { code: 'Zvt', name: 'Zandvoort aan Zee' },
  { code: 'Za', name: 'Zetten-Andelst' },
  { code: 'Zv', name: 'Zevenaar' },
  { code: 'Zvb', name: 'Zevenbergen' },
  { code: 'Ztm', name: 'Zoetermeer' },
  { code: 'Ztmo', name: 'Zoetermeer Oost' },
  { code: 'Zb', name: 'Zuidbroek' },
  { code: 'Zh', name: 'Zuidhorn' },
  { code: 'Zp', name: 'Zutphen' },
  { code: 'Zwd', name: 'Zwijndrecht' },
  { code: 'Zl', name: 'Zwolle' },
  { code: 'Zlsh', name: 'Zwolle Stadshagen' },
  { code: 'Zzs', name: 'Zaandijk Zaanse Schans' },
];